version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.PAT}}
updates:
  - package-ecosystem: 'npm'
    registries:
      - npm-github
    directory: '/'
    versioning-strategy: 'increase'
    commit-message:
      prefix: 'fix'
      include: 'scope'
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'Asia/Bangkok'
