name: 🚀 NPM Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@ahiho'
      - name: Build
        run: yarn ci:install && yarn ci:build
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}
      - name: Release
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          yarn ci:release --no-private
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          NODE_AUTH_TOKEN: ${{ github.token }}
