name: 📦 Publish NPM

on:
  release:
    types:
      - published

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}
          scope: "@ahiho"

      - run: yarn ci:install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}

      - run: echo "PACKAGE=$(sed -e s:@[^@]*$::g <<< ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
      - run: echo "RELEASE_VERSION=$(sed -e s:.*@::g <<< ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV

      - run: |
          yarn nx publish-npm ${PACKAGE} --ver ${RELEASE_VERSION}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
