name: 📦

on:
  release:
    types: [published]

jobs:
  publish_npm:
    name: Publish npm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com/
          scope: '@ahiho'
      - name: Build
        run: yarn ci:install && yarn ci:build
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}
      - name: Publish
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          find packages -type d -maxdepth 1 -exec cp .npmrc {} \;
          npx lerna publish from-git --conventional-commits false --yes --registry https://registry.npmjs.org --no-verify-access
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
