name: 📦

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@ahiho'
      - name: Build
        run: yarn ci:install && yarn ci:build
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}
      - name: Publish
        run: |
          npx lerna publish from-git --yes --registry https://npm.pkg.github.com
          git reset --hard
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
          npx lerna publish from-git --yes --registry https://registry.npmjs.org
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          NODE_AUTH_TOKEN: ${{ github.token }}

